#!/usr/bin/env bash

me="$(basename "$0")";
running=$(ps h -C "$me" | grep -wv $$ | wc -l);
[[ $running > 1 ]] && exit;

time=4
bias=0

if [[ "$1" == "lower" ]]
then
    bias=-1
elif [[ "$1" == "raise" ]]
then
    bias=1
fi

light=$(cat /sys/class/backlight/acpi_video0/brightness)
biased=$(echo "scale=2; $light + $bias" | bc)
scaled=$(echo "scale=2; ($light + $bias) / 15.0" | bc)

alpha="0.5"

if [ "$biased" -lt "6" ]
then
    avizo-client --image-resource="brightness_low" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
elif [ "$biased" -lt "11" ]
then
    avizo-client --image-resource="brightness_medium" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
elif [ "$biased" -lt "16" ]
then
    avizo-client --image-resource="brightness_high" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
fi

