#!/usr/bin/env bash

me="$(basename "$0")";
running=$(ps h -C "$me" | grep -wv $$ | wc -l);
[[ $running > 1 ]] && exit;

time=4

if [[ "$1" == "lower" ]]
then
    echo `amixer set Master 5%-` > /dev/null
elif [[ "$1" == "raise" ]]
then
    echo `amixer set Master 5%+` > /dev/null
elif [[ "$1" == "mute" ]]
then
    echo `amixer set Master toggle` > /dev/null
fi

vol=$(amixer get Master | grep -Po "[0-9]+(?=%)" | tail -1)
off=$(amixer get Master | grep -o "off" | head -n 1)

alpha="0.5"

if [[ "$1" == "mute" && "$off" != *"off"* ]]
then
    avizo-client --image-resource="volume_muted" --progress="0" --time=$time --background="rgba(255, 255, 255, $alpha)"
else
    scaled=$(echo "scale=2; $vol / 100.0" | bc)
    echo $scaled

    if [ "$vol" -lt "34" ]
    then
        avizo-client --image-resource="volume_low" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
    elif [ "$vol" -lt "67" ]
    then
        avizo-client --image-resource="volume_medium" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
    elif [ "$vol" -lt "101" ]
    then
        avizo-client --image-resource="volume_high" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
    fi
fi

